import type { MetadataRoute } from 'next';

const BASE_URL = 'https://toplineplumbingco.com';

const routes = [
  '/',
  '/about',
  '/services',
  '/services/drain-cleaning',
  '/services/emergency',
  '/services/fixture-installs',
  '/services/gas-line',
  '/services/leak-detection',
  '/services/repiping-services',
  '/services/sewer-line',
  '/services/tankless',
  '/services/water-heater-repair',
  '/areas',
  '/areas/anderson',
  '/areas/bella-vista',
  '/areas/palo-cedro',
  '/areas/red-bluff',
  '/areas/redding',
  '/areas/shasta-lake',
  '/commercial-plumbing-redding',
  '/water-heater-replacement-redding',
  '/drain-cleaning-anderson',
  '/drain-cleaning-bella-vista',
  '/drain-cleaning-palo-cedro',
  '/drain-cleaning-red-bluff',
  '/drain-cleaning-redding',
  '/drain-cleaning-shasta-lake',
  '/emergency-plumber-anderson',
  '/emergency-plumber-bella-vista',
  '/emergency-plumber-palo-cedro',
  '/emergency-plumber-red-bluff',
  '/emergency-plumber-redding',
  '/emergency-plumber-shasta-lake',
  '/sewer-line-anderson',
  '/sewer-line-bella-vista',
  '/sewer-line-palo-cedro',
  '/sewer-line-red-bluff',
  '/sewer-line-redding',
  '/sewer-line-shasta-lake',
  '/water-heater-repair-anderson',
  '/water-heater-repair-bella-vista',
  '/water-heater-repair-palo-cedro',
  '/water-heater-repair-red-bluff',
  '/water-heater-repair-shasta-lake',
  '/contact',
  '/faq',
  '/gallery',
  '/resources',
  '/resources/burst-pipe-emergency-guide',
  '/resources/how-to-shut-off-main-water-valve',
  '/resources/water-heater-failure-warning-signs',
  '/privacy',
  '/terms',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified,
    changeFrequency: route === '/' ? 'weekly' : 'monthly',
    priority: route === '/' ? 1 : 0.7,
  }));
}
